apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
  name: {{ .Release.Namespace }}-{{ .Release.Name }}
  namespace: istio-system
spec:
  secretName: {{ .Release.Namespace }}-{{ .Release.Name }}
  duration: 2160h
  renewBefore: 360h
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames: 
    - grand-universe.com
    - www.grand-universe.com
  issuerRef:
    name: {{ .Release.Namespace }}-{{ .Release.Name }}
    kind: ClusterIssuer
