apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  host: {{ .Release.Name }}
  {{- if .Values.gateway.consistentHash }}
  trafficPolicy:
    loadBalancer:
      consistentHash:
        useSourceIp: true
  {{- end }}
