name: GrandUniverse Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: grand-universe-website-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  NAMESPACE: production

jobs:
  push-docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/grand-universe-website:${{ github.sha }},${{ env.DOCKER_REGISTRY }}/grand-universe-website:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - push-docker
    steps:
      - uses: actions/checkout@v3
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Deploy ${{ matrix.product.name }}
        shell: bash
        run: |
          helm -n production upgrade grand-universe-website \
            --install ./kubernetes \
            --set image.tag=${{ github.sha }} \
            -f ./kubernetes/values.yaml
